version: "3.9"

services:
  judy-du-nextjs-app-main:
    image: vicmrp/mixedenergy-app-main:nodejs22-1.0.0
    user: node
    command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - ..:/usr/src/project
